[project]
name = "anime-parsers-ru"
version = "0.0.1"
authors = [
  { name="YaNesyTortiK", email="ya.nesy.tortik.email@gmail.com"},
]
description = "Python package for parsing ru anime players"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/-In Work-"
Issues = "https://github.com/-In Work-/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"